version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    container_name: nest_api
    command: sh -c -f "yarn schema:update&&yarn run start:prod"
    restart: unless-stopped
    env_file: ./.env
    ports:
      - '${PORT:-3000}:3000'
    depends_on:
      - postgresdb
    networks:
      - app_network
    volumes:
      - ./public:/app/public
      - ./uploads:/app/uploads
    stdin_open: true
    tty: true
  postgresdb:
    image: postgres:15
    container_name: nest_postgres
    restart: always
    ports:
      - '${DB_PORT:-5432}:5432'
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./docker/init/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app_network
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - app_network 
volumes:
  pgdata:
  pgadmin-data:

networks:
  app_network:
    driver: bridge
